'''--- Day 11: Cosmic Expansion ---
You continue following signs for "Hot Springs" and eventually come across an observatory. The Elf within turns out to be a researcher studying cosmic expansion using the giant telescope here.

He doesn't know anything about the missing machine parts; he's only visiting for this research project. However, he confirms that the hot springs are the next-closest area likely to have people; he'll even take you straight there once he's done with today's observation analysis.

Maybe you can help him with the analysis to speed things up?

The researcher has collected a bunch of data and compiled the data into a single giant image (your puzzle input). The image includes empty space (.) and galaxies (#). For example:

...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
The researcher is trying to figure out the sum of the lengths of the shortest path between every pair of galaxies. However, there's a catch: the universe expanded in the time it took the light from those galaxies to reach the observatory.

Due to something involving gravitational effects, only some space expands. In fact, the result is that any rows or columns that contain no galaxies should all actually be twice as big.

In the above example, three columns and two rows contain no galaxies:

   v  v  v
 ...#......
 .......#..
 #.........
>..........<
 ......#...
 .#........
 .........#
>..........<
 .......#..
 #...#.....
   ^  ^  ^
These rows and columns need to be twice as big; the result of cosmic expansion therefore looks like this:

....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
Equipped with this expanded universe, the shortest path between every pair of galaxies can be found. It can help to assign every galaxy a unique number:

....1........
.........2...
3............
.............
.............
........4....
.5...........
............6
.............
.............
.........7...
8....9.......
In these 9 galaxies, there are 36 pairs. Only count each pair once; order within the pair doesn't matter. For each pair, find any shortest path between the two galaxies using only steps that move up, down, left, or right exactly one . or # at a time. (The shortest path between two galaxies is allowed to pass through another galaxy.)

For example, here is one of the shortest paths between galaxies 5 and 9:

....1........
.........2...
3............
.............
.............
........4....
.5...........
.##.........6
..##.........
...##........
....##...7...
8....9.......
This path has length 9 because it takes a minimum of nine steps to get from galaxy 5 to galaxy 9 (the eight locations marked # plus the step onto galaxy 9 itself). Here are some other example shortest path lengths:

Between galaxy 1 and galaxy 7: 15
Between galaxy 3 and galaxy 6: 17
Between galaxy 8 and galaxy 9: 5
In this example, after expanding the universe, the sum of the shortest path between all 36 pairs of galaxies is 374.

Expand the universe, then find the length of the shortest path between every pair of galaxies. What is the sum of these lengths?'''

test_input = '''...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....'''
test_answer = 374

def get_expanse_rows_cols(m):
    '''Gets expanse rows and cols.
    Expects m to have a length > 0.'''
    rows, cols = [], []
    # Getting rows
    for i in range(len(m)):
        if '#' not in m[i]:
            rows.append(i)
    # Getting cols
    for col in range(len(m[0])):
        galaxy_found = False
        for row in range(len(m)):
            if m[row][col] == '#':
                galaxy_found = True
                break
        if not galaxy_found:
            cols.append(col)
    return rows, cols

def get_galaxy_coords(m):
    coords = []
    for row in range(len(m)):
        for col in range(len(m[row])):
            if m[row][col] == '#':
                coords.append([row, col])
    return coords

def adjust_coords_for_expanse(galaxy_coords, rows, cols):
    # Adjusting the row (or x) part of the galaxy_coords
    for i in range(len(galaxy_coords)):
        num_expanses = 0
        for row in rows:
            if row < galaxy_coords[i][0]:
                num_expanses += 1
        galaxy_coords[i][0] += num_expanses
    # Adjusting the col (or y) part of the galaxy_coords
    for i in range(len(galaxy_coords)):
        num_expanses = 0
        for col in cols:
            if col < galaxy_coords[i][1]:
                num_expanses += 1
        galaxy_coords[i][1] += num_expanses

def get_sum_of_shortest_path_for_galaxy_pairs(galaxy_coords):
    '''This function gets the sumation of the shortest paths of each pair of
    galaxies.'''
    total = 0
    for i in range(len(galaxy_coords)):
        for j in range(i + 1, len(galaxy_coords)):
            total += abs(galaxy_coords[i][0] - galaxy_coords[j][0]) + abs(galaxy_coords[i][1] - galaxy_coords[j][1])
    return total

if __name__ == '__main__':
    with open('2023/11/input_galaxy.txt', 'r') as f:
        m = f.read().split('\n')[:-1]
    expanse_rows, expanse_cols = get_expanse_rows_cols(m)
    galaxy_coords = get_galaxy_coords(m)
    adjust_coords_for_expanse(galaxy_coords, expanse_rows, expanse_cols)
    total_distance = get_sum_of_shortest_path_for_galaxy_pairs(galaxy_coords)
    print(f'total_distance:{total_distance}')

